# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Projects
    url: projects/
    weight: 20
  - name: Publications
    url: publications/
    weight: 30
  - name: Utils
    url: utils/
    identifier: utils
    weight: 40
  - name: Lost and Found
    parent: utils
    url: utils/lost_and_found
    weight: 10
  
  # - name: News
  #   url: news/
  #   weight: 40
